### ISSUE TITLE
Decide on a compatibility policy

### ISSUE THREAD

**Issue by mary-kate** [harej/purple#1]
It's possible to (maybe even heavily) optimize `assets/stylesheets/purple.css` by leveraging `$wgResourceModuleSkinStyles` like how [Refreshed](https://www.mediawiki.org/wiki/Skin:Refreshed) and other skins do. This allows skins to "piggyback" on core ResourceLoader modules and thus reduce the size of the CSS loaded for all users on all page views.

However this doesn't work correctly on some older versions of MediaWiki. (Likewise, a similar but less practical question would be long vs. short array syntax -- MediaWiki coding conventions nowadays recommend short array syntax and jenkins even complains if you try using long array syntax IIRC. On the other hand, sometimes you need to do [stupid compatibility hacks](https://github.com/wikimedia/mediawiki-skins-MonoBook/commit/ab8afffce278e93e16c868c489a2546070b6b453) for newer versions of PHP.)

cc'ing @SamanthaNguyen for thoughts

**Comment by harej** [comment]
I prefer short array syntax.

As for backwards compatibility, since this is a brand new skin with no users yet, *and* I am interested in Purple being a forward-thinking skin ready to adapt to future uses without being burdened by legacy code, I am happy to have compatibility track the MediaWiki release cycle. In other words, we should not guarantee support for any version below 1.27 (the current LTS version), and as 1.27 and other versions reach EOL, we no longer guarantee support for them.
